# Generated by Django 5.0.1 on 2025-03-20 19:31

import useraccount.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', useraccount.models.CustomUserManager()),
            ],
        ),
    ]
