# Generated by Django 5.0.1 on 2025-03-26 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='baehrooms',
            new_name='bathrooms',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='bedroomd',
            new_name='bedrooms',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='guest',
            new_name='guests',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='price_per_nigth',
            new_name='price_per_night',
        ),
    ]
