# Generated by Django 5.0.1 on 2025-03-31 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_favorited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
